version: '3.7'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    networks:
      - my-network

  redis-commander:
    image: 'rediscommander/redis-commander:latest'
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - my-network

  producer-consumer:
    build:
      context: .
    depends_on:
      - redis
    networks:
      - my-network
    ports:
      - "8080:8080"

networks:
  my-network:
    driver: bridge
